baseURL = 'https://joshuahemmings.ch'
languageCode = 'en-us'
title = 'Joshua Hemmings'
theme = "awesome-identity"

## Profile Configurations
[params.profile]
portrait = "/images/Hemmings_Joshua_B.jpg"
firstname = "Joshua"
lastname = "Hemmings"
title = "DevOps Expert & MSc Applied Information and Data Science student"
bio = """
Hi there, I'm **Josh** and I currently work Open Web Technology in the role of a "DevOps Expert". Previously I worked for
the Lucerne University of Applied Sciences (HSLU). For HSLU I created automation for course infrastructure using Packer,
Terraform and Ansible.

Feel free to get in touch!
  """

# socials
[params.contacts]
email = "joshua@hemmings.ch"
github = "jLemmings"
gitlab = "jLemmings"
linkedin = "joshua-hemmings-b17478117"

## Footer Configurations
[params.footer]
copyright = "© 2022 Joshua Hemmings"
poweredBy = false
